In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [ ]:
import tensorflow as tf
import numpy as np

# Exercise on basic Tensor operations

In [ ]:
# Create a 1D uint8 NumPy array comprising of first 9 natural numbers
x = np.arange(1, 10)
x

In [ ]:
# Convert NumPy array to Tensor using `tf.constant`
def tf_constant(array):
    
    ### START CODE HERE ###
    tf_constant_array = tf.constant(array)
    ### END CODE HERE ###
    return tf_constant_array

In [ ]:
x = tf_constant(x)
x

# Expected output:
# <tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
# Square the input tensor x
def tf_square(array):
    
    ### START CODE HERE ###
    tf_squared_array = tf.square(array)
    ### END CODE HERE ###
    return tf_squared_array

In [ ]:
x = tf_square(x)
x

# Expected output:
# <tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# Reshape tensor x into a 3 x 3 matrix
def tf_reshape(array, shape):
    
    ### START CODE HERE ###
    tf_reshaped_array = tf.reshape(array, shape)
    ### END CODE HERE ###
    return tf_reshaped_array

In [ ]:
x = tf_reshape(x, (3, 3))
x

# Expected output:
# <tf.Tensor: shape=(3, 3), dtype=int64, numpy=
#
# [[  1.,   4.,  9.],
#  [ 16.,  25.,  36.],
#  [ 49., 64., 81.]]

In [ ]:
# Cast tensor x into float32 
def tf_cast(array, dtype):
    
    ### START CODE HERE ###
    tf_cast_array = tf.cast(array, dtype)
    ### END CODE HERE ###
    return tf_cast_array

In [ ]:
x = tf_cast(x, tf.float32)
x

# Expected output:
# <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
#
# [[  1.,   4.,  9.],
#  [ 16.,  25.,  36.],
#  [ 49., 64., 81.]]

In [ ]:
y = tf.constant(2, dtype=tf.float32)
y

In [ ]:
# Multiply tensor x and y
def tf_multiply(num1, num2):
    
    ### START CODE HERE ###
    product = tf.multiply(num1, num2)
    ### END CODE HERE ###
    return product


In [ ]:
result = tf_multiply(x, y)
result.numpy()


# Expected output:
# [[  2.,   8.,  18.],
#  [ 32.,  50.,  72.],
#  [ 98., 128., 162.]]

In [ ]:
y = tf.constant([1, 2, 3], dtype=tf.float32)
y

In [ ]:
# Add tensor x and y
def tf_add(num1, num2):
    
    ### START CODE HERE ###
    sum = num1 + num2
    ### END CODE HERE ###
    return sum

In [ ]:
result = tf_add(x, y)
result

# Expected output:
# [[ 2.,  6., 12.],
#  [17., 27., 39.],
#  [50., 66., 84.]]

# Exercise on Gradient Tape

In [ ]:
def tf_gradient_tape(x):
    
    with tf.GradientTape() as t:
        
    ### START CODE HERE ###
        # Record the actions performed on tensor x with `watch`
        t.watch(x)  

        # Define a polynomial of form 3x^3 - 2x^2 + x
        y =  3 * (x ** 3) - 2 * (x ** 2)  + x    

        # Obtain the sum of variable y
        z = tf.reduce_sum(y) 
  
    # Derivative of z wrt the original input tensor x
    dz_dx = t.gradient(z, x)
    ### END CODE HERE
    
    return dz_dx

In [ ]:
x = tf.constant(2.0)

tf_gradient_tape(x)

In [ ]:
# Convert dz_dx into NumPy 
dz_dx = tf_gradient_tape(x)

result = dz_dx.numpy()
result

# Expected output:
# 29.0