In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Basic Tensor operations

In this graded assignment, you will perform different tensor operations using Tensorflow. For more information on the internals of this library be sure to check the [official docs](https://www.tensorflow.org/api_docs/python/tf).

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Create a 1D uint8 NumPy array comprising of first 9 natural numbers
x = np.arange(1, 10)
x

## Exercise 1 - [tf.constant]((https://www.tensorflow.org/api_docs/python/tf/constant))

Creates a constant tensor from a tensor-like object. 

In [ ]:
# Convert NumPy array to Tensor using `tf.constant`
def tf_constant(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        tensorflow.python.framework.ops.EagerTensor: tensor.
    """
    ### START CODE HERE ###
    tf_constant_array = None
    ### END CODE HERE ###
    return tf_constant_array

In [ ]:
x = tf_constant(x)
x

# Expected output:
# <tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

Note that for future docstrings the type `EagerTensor` will be used as a shortened version of `tensorflow.python.framework.ops.EagerTensor`.

## Exercise 2 - [tf.square](https://www.tensorflow.org/api_docs/python/tf/math/square)

Computes square of x element-wise.

In [ ]:
# Square the input tensor x
def tf_square(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        EagerTensor: tensor.
    """
    ### START CODE HERE ###
    tf_squared_array = None
    ### END CODE HERE ###
    return tf_squared_array

In [ ]:
x = tf_square(np.arange(41, 50))
x

# Expected output:
# <tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

## Exercise 3 - [tf.reshape](https://www.tensorflow.org/api_docs/python/tf/reshape)

Reshapes a tensor.

In [ ]:
# Reshape tensor x into a 3 x 3 matrix
def tf_reshape(array, shape):
    """
    Args:
        array (EagerTensor): tensor to reshape.
        shape (tuple): desired shape.

    Returns:
        EagerTensor: reshaped tensor.
    """
    ### START CODE HERE ###
    tf_reshaped_array = None
    ### END CODE HERE ###
    return tf_reshaped_array

In [ ]:
x = tf_reshape(x, (3, 3))
x

# Expected output:
# <tf.Tensor: shape=(3, 3), dtype=int64, numpy=
#
# [[  1.,   4.,  9.],
#  [ 16.,  25.,  36.],
#  [ 49., 64., 81.]]

## Exercise 4 - [tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast)

Casts a tensor to a new type.

In [ ]:
# Cast tensor x into float32 
def tf_cast(array, dtype):
    """
    Args:
        array (EagerTensor): tensor to be casted.
        dtype (tensorflow.python.framework.dtypes.DType): desired new type. (Should be a TF dtype!)

    Returns:
        EagerTensor: casted tensor.
    """
    ### START CODE HERE ###
    tf_cast_array = None
    ### END CODE HERE ###
    return tf_cast_array

In [ ]:
x = tf_cast(x, tf.float32)
x

# Expected output:
# <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
#
# [[  1.,   4.,  9.],
#  [ 16.,  25.,  36.],
#  [ 49., 64., 81.]]

## Exercise 5 - [tf.multiply](https://www.tensorflow.org/api_docs/python/tf/multiply)

Returns an element-wise x * y.

In [ ]:
y = tf.constant(2, dtype=tf.float32)
y

In [ ]:
# Multiply tensor x and y
def tf_multiply(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    ### START CODE HERE ###
    product = None
    ### END CODE HERE ###
    return product


In [ ]:
result = tf_multiply(x, y)
result.numpy()


# Expected output:
# [[  2.,   8.,  18.],
#  [ 32.,  50.,  72.],
#  [ 98., 128., 162.]]

## Exercise 6 - [tf.add](https://www.tensorflow.org/api_docs/python/tf/add)

Returns x + y element-wise.

In [ ]:
y = tf.constant([1, 2, 3], dtype=tf.float32)
y

In [ ]:
# Add tensor x and y
def tf_add(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    ### START CODE HERE ###
    sum = None
    ### END CODE HERE ###
    return sum

In [ ]:
result = tf_add(x, y)
result

# Expected output:
# [[ 2.,  6., 12.],
#  [17., 27., 39.],
#  [50., 66., 84.]]

## Exercise 7 - Gradient Tape

Implement the function `tf_gradient_tape`.

Check the [docs](https://www.tensorflow.org/api_docs/python/tf/GradientTape) for a better idea of how this works.

In [ ]:
def tf_gradient_tape(x):
    """
    Args:
        x (EagerTensor): a tensor.

    Returns:
        EagerTensor: Derivative of z with respect to the input tensor x.
    """
    with tf.GradientTape() as t:
        
    ### START CODE HERE ###
        # Record the actions performed on tensor x with `watch`
        t.watch(x)   

        # Define a polynomial of form 3x^3 - 2x^2 + x
        y = None

        # Obtain the sum of variable y
        z = None
  
    # Derivative of z wrt the original input tensor x
    dz_dx = None
    ### END CODE HERE
    
    return dz_dx

In [ ]:
x = tf.constant(2.0)

tf_gradient_tape(x)

In [ ]:
# Convert dz_dx into NumPy 
dz_dx = tf_gradient_tape(x)

result = dz_dx.numpy()
result

# Expected output:
# 29.0

**Congratulations on finishing this week's assignment!** Now you should be more familiar with the basic tensor operations that Tensorflow allows. 

**Keep it up!**